#!/usr/bin/env bash
# Regenerate the Rust model files used by the judge (server/src/generated/).
#
# The judge compiles XGBoost into Rust via m2cgen so it can score submissions
# in-process with zero runtime deps. Run this after retraining a model.
#
# Usage:  ./regenerate_models.sh
# Requires: a Python venv at ./venv with `m2cgen` and `joblib` installed.
#
# NOTE: model-training's venv script is `./.venv/bin/python` (hidden dir).
# If you use a different venv path, edit PY below.
set -euo pipefail
cd "$(dirname "$0")"

PY="${1:-./.venv/bin/python}"
export OUT="../server/src/generated"
mkdir -p "$OUT"

# Base score: XGBoost 3.x stores base_score=None but the true offset is 0.5.
# m2cgen crashes on None, so we set it explicitly (does NOT change predictions).
"$PY" - <<'PY'
import m2cgen as m2c, joblib, os
outdir = os.environ["OUT"]
# artifact basename (joblib) -> model key, feature count, output rust filename
jobs = [
    ("model_specialized_python", "python", 32, "specialized_python.rs"),
    ("model_specialized_cpp",    "cpp",   32, "specialized_cpp.rs"),
    ("model_specialized_java",   "java",  32, "specialized_java.rs"),
    ("model_unified_multi-language", "unified", 36, "unified_multi_language.rs"),
]
for job, key, nfeat, fname in jobs:
    m = joblib.load(f"artifacts/{job}.joblib")
    m.base_score = 0.5  # fix XGBoost 3.x None bug for m2cgen
    src = m2c.export_to_rust(m, function_name="score")
    # guard: verify feature count matches what predict.rs feeds
    path = os.path.join(outdir, fname)
    with open(path, "w") as f:
        f.write(f"// Auto-generated by model-training/regenerate_models.sh — DO NOT EDIT.\n")
        f.write(f"// model={job}  features={nfeat}  xgboost->m2cgen\n")
        f.write("// Generator: `m2cgen.export_to_rust` with base_score=0.5\n")
        # make score public so the sibling predict module can reach it
        src = src.replace("fn score(", "pub fn score(", 1)
        f.write(src)
    print(f"wrote {fname} ({nfeat} features)")
PY
echo "Done. Next: rebuild the judge  ->  cd server && cargo build"
